# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14
trigger:
- master
pool:
  name: Default

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'ansible-playbook/test_azure.yaml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'ansible-playbook/inventory'
    args: '--extra-vars "image=${{ parameters.image }}"'

