---
- name: Test run
  hosts: localhost
  collections:
  - name: community.aws
    version: 3.1.1
  tasks:
  - name: test
    community.aws.sts_assume_role:
      role_arn: "arn:aws:iam::123456789012:role/someRole"
      role_session_name: "someRoleSession"
    register: assumed_role
    
      
