---
- name: playbook to test cron module
  hosts: localhost
  tasks:
    - name: scheduling a cron job
      cron:
        name: test
        user: avijit
        job: " echo hello world"
        minute: '*'
        state: absent
