---
- name: user module playbook
  hosts: db
  vars:
    - user: rango
    - password: redhat
  tasks:
    - name: creating a user rango
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present

    - name: installing ssh key based authentication
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '/home/avijit/.ssh/id_rsa.pub') }}"
