name: My Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
  # to detect PR creation/updates and merge

jobs:
  common-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run common tasks
        run: echo "Running group of common tasks"
